### ISSUE TITLE
Release on NuGet

### ISSUE THREAD

**Issue by dominik-weber** [Microsoft/ApplicationInsights-Xamarin#23]
Please release the current version(s) on NuGet so we can use VSTS build agents.

**Comment by Cheesebaron** [comment]
See https://github.com/Microsoft/ApplicationInsights-Xamarin/issues/19

Aparently these guys are not going to do this. The issue was marked as wontfix without reason, this one probably will too. :clap: 

According to this one: https://github.com/Microsoft/ApplicationInsights-Xamarin/issues/6 they won't release a NuGet until beta status. However, looking at the commit history, that is never going to happen.

**Comment by ghost** [comment]
As @Cheesebaron mentioned, we are not going to release the SDK on NuGet. However, I added an alpha 3 nupkg to the repo. Can you use local NuGet sources in your VSTS build definition?
