### ISSUE TITLE
Xamarin Android not Logging Telemetry

### ISSUE THREAD

**Issue by pottabathini** [Microsoft/ApplicationInsights-Xamarin#25]
We able to integrate Applicaiton insights in the xamarin forms and able to get the telemetry for iOS. Same not working with Android. When we run android on output below message is showing

`05-17 16:57:11.153 W/art     (  677): JNI RegisterNativeMethods: attempt to register 0 native methods for md531a9393487f6e844970cf7436e0f56cf.ApplicationInsights
05-17 16:57:11.153 D/Mono    (  677): Assembly Ref addref AI.XamarinSDK.Android[0xaefd69a0] -> Xamarin.Forms.Platform.Android[0xaee2db20]: 7
05-17 16:57:11.153 D/Mono    (  677): Assembly Ref addref AI.XamarinSDK.Android[0xaefd69a0] -> AI.XamarinSDK.AndroidBindings[0xaefd6760]: 2
05-17 16:57:11.223 D/Mono    (  677): Assembly Ref addref ODISMember.Services[0xaee2a880] -> AI.XamarinSDK.Abstractions[0xaefd67c0]: 4
05-17 16:57:11.223 I/System.out(  677): Sending Operation Instance 1
05-17 16:57:16.768 W/art     (  677): JNI RegisterNativeMethods: attempt to register 0 native methods for md531a9393487f6e844970cf7436e0f56cf.TelemetryManager
05-17 16:57:16.823 D/OpenGLRenderer(  677): Render dirty regions requested: true
05-17 16:57:16.998 I/        (  677): PLATFORM VERSION : JB-MR-2
05-17 16:57:17.003 I/OpenGLRenderer(  677): Initialized EGL, version 1.4`

How can we fix this strange issue. We used both motorola andsamsung devices which all below the verion of 5.0.1 and below

**Comment by ElektrojungeAtWork** [comment]
This SDK is officially deprecated. Please switch to [HockeyApp](https://hockeyapp.net) or consider [MobileCenter](https://www.visualstudio.com/vs/mobile-center/).

Hey @pottabathini,

I just saw your issue here. Note that the SDK has been deprecated, please switch to HockeyApp or consider the all new Mobile Center.

You can find more about the transition from Application Insights to HockeyApp [here](https://www.hockeyapp.net/blog/2016/03/11/welcome-application-insights-users.html) and about how Mobile Center will be the future of HockeyApp [here](https://www.hockeyapp.net/blog/2016/11/16/mobile-center-next-generation-hockeyapp.html).

Please don't hesitate to get in touch via [support@hockeyapp.net](mailto:support@hockeyapp.net).
 if you have questions.

Best,
Benjamin
